language: nix
matrix:
    include:
        - os: linux
          sudo: false
          script:
              - ./dobuilds.sh ./default.nix
              - nix-shell -p tree --run "tree /nix/var/log/nix/drvs/"
